# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Assignment 8 book
author: Clifford Childs
logo: images/frozen.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/CliffordCC/final-assignment-8  # Online location of your book
  path_to_book: final-assignment-8/assignment-8-book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "jupyterlab"  # or "classic"
  thebe                  : true
  binderhub_url: "https://mybinder.org"  # The URL for your BinderHub